/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import Vista.VentanaDevoluciones;
import Vista.VentanaLibros;
import Vista.VentanaPrestamos;
import Vista.Principal1;
import Vista.VentanaRegistros; 
import Vista.VentanaUsuarios;
import java.awt.BorderLayout;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JPanel;
import java.time.LocalDateTime;
import javax.swing.Timer;

/**
 *
 * @author angel
 */
public class Raiz extends javax.swing.JFrame {

    /**
     * Creates new form Raiz
     */
     public Raiz() {
        initComponents();   // Inicializa los componentes del formulario
        startClock();       // Inicia el reloj en tiempo real
        inicioPanel();      // Carga el panel inicial
    }
    private void inicioPanel(){
        showPanel(new Principal1());
    }
    //Esta parte del codigo hace que se muestre la ventana  en un panel y lo hice un metodo
    private void showPanel(JPanel p){
        p.setSize(1020, 610);
        p.setLocation(0,0);
        
        contenido.removeAll();
        contenido.add(p, BorderLayout.CENTER);
        contenido.revalidate();
        contenido.repaint();
    }   
       LocalDate now = LocalDate.now();     
     //para mostrar la hora 
      // Inicia un reloj que actualiza cada segundo
    private void startClock() {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("  dd/MM/yy     HH:mm:ss");

    Timer timer = new Timer(1000, e -> {
        LocalDateTime now = LocalDateTime.now();
        Fecha.setText(now.format(formatter));
    });

    timer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        BotonUsuarios = new javax.swing.JButton();
        BotonVentanaPrincipal1 = new javax.swing.JButton();
        BotonPrestamos = new javax.swing.JButton();
        BotonDevoluciones = new javax.swing.JButton();
        BotonLibros = new javax.swing.JButton();
        BotonRegristros = new javax.swing.JButton();
        contenido = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(255, 255, 255));

        Menu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("SimSun-ExtB", 0, 12)); // NOI18N

        Texto.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Texto.setForeground(new java.awt.Color(51, 51, 51));
        Texto.setText("Falculdad de ingeneria/control/biblioteca");

        Fecha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Fecha.setForeground(new java.awt.Color(0, 0, 0));

        BotonUsuarios.setBackground(new java.awt.Color(204, 204, 204));
        BotonUsuarios.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonUsuarios.setText("Usuarios");
        BotonUsuarios.setBorder(null);
        BotonUsuarios.setBorderPainted(false);
        BotonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUsuariosActionPerformed(evt);
            }
        });

        BotonVentanaPrincipal1.setBackground(new java.awt.Color(204, 204, 204));
        BotonVentanaPrincipal1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonVentanaPrincipal1.setText("Principal");
        BotonVentanaPrincipal1.setBorder(null);
        BotonVentanaPrincipal1.setBorderPainted(false);
        BotonVentanaPrincipal1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonVentanaPrincipal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVentanaPrincipal1ActionPerformed(evt);
            }
        });

        BotonPrestamos.setBackground(new java.awt.Color(204, 204, 204));
        BotonPrestamos.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonPrestamos.setText("Prestamos");
        BotonPrestamos.setBorder(null);
        BotonPrestamos.setBorderPainted(false);
        BotonPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BotonPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrestamosActionPerformed(evt);
            }
        });

        BotonDevoluciones.setBackground(new java.awt.Color(204, 204, 204));
        BotonDevoluciones.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonDevoluciones.setText("Devoluciones");
        BotonDevoluciones.setBorder(null);
        BotonDevoluciones.setBorderPainted(false);
        BotonDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDevolucionesActionPerformed(evt);
            }
        });

        BotonLibros.setBackground(new java.awt.Color(204, 204, 204));
        BotonLibros.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonLibros.setText("Libros");
        BotonLibros.setBorder(null);
        BotonLibros.setBorderPainted(false);
        BotonLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLibrosActionPerformed(evt);
            }
        });

        BotonRegristros.setBackground(new java.awt.Color(204, 204, 204));
        BotonRegristros.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        BotonRegristros.setText("Registros");
        BotonRegristros.setBorder(null);
        BotonRegristros.setBorderPainted(false);
        BotonRegristros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegristrosActionPerformed(evt);
            }
        });

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setPreferredSize(new java.awt.Dimension(1020, 640));

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 966, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(BotonVentanaPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(BotonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(BotonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(BotonLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addComponent(Texto, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 222, Short.MAX_VALUE)
                        .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout.createSequentialGroup()
                                .addComponent(BotonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(BotonRegristros, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))))))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Texto)
                    .addComponent(Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonVentanaPrincipal1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonDevoluciones, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BotonRegristros, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //boton registro 
    private void BotonRegristrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegristrosActionPerformed
        // TODO add your handling code here:
        //boton para  llamar a la ventana Registro
        showPanel(new VentanaRegistros());
    }//GEN-LAST:event_BotonRegristrosActionPerformed

    private void BotonLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLibrosActionPerformed
        // TODO add your handling code here:
        //boton para llamar a la ventana libros
        showPanel(new VentanaLibros());
    }//GEN-LAST:event_BotonLibrosActionPerformed

    private void BotonDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDevolucionesActionPerformed
        // TODO add your handling code here:
        //boton para llamar a la ventana devoluciones
        showPanel(new VentanaDevoluciones());
    }//GEN-LAST:event_BotonDevolucionesActionPerformed

    private void BotonPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrestamosActionPerformed
        // TODO add your handling code here:
        //boton para llamar a la ventana prestamos
        showPanel(new VentanaPrestamos());
    }//GEN-LAST:event_BotonPrestamosActionPerformed

    private void BotonVentanaPrincipal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVentanaPrincipal1ActionPerformed
        // TODO add your handling code here:
        //codigo para llamar a la ventana principal
        showPanel(new Principal1());

    }//GEN-LAST:event_BotonVentanaPrincipal1ActionPerformed

    private void BotonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUsuariosActionPerformed
        // TODO add your handling code here:
        //boton para llamar a a la ventana Usuario
        showPanel(new VentanaUsuarios());
    }//GEN-LAST:event_BotonUsuariosActionPerformed

    /**
     * @param args the command line arguments 
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Raiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Raiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Raiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Raiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Raiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonDevoluciones;
    private javax.swing.JButton BotonLibros;
    private javax.swing.JButton BotonPrestamos;
    private javax.swing.JButton BotonRegristros;
    private javax.swing.JButton BotonUsuarios;
    private javax.swing.JButton BotonVentanaPrincipal1;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel Menu;
    private javax.swing.JLabel Texto;
    private javax.swing.JPanel background;
    private javax.swing.JPanel contenido;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    private void initSytiles() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
