/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author angel
 */
import Conexiones.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import org.hsqldb.types.Types;

public class VentanaUsuarios extends javax.swing.JPanel {

    private Conexion conexion;

    /**
     * Creates new form Principal1
     */
    public VentanaUsuarios() {

        initComponents();
        conexion = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JTextField();
        IDLibro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDLibro1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IDLibro2 = new javax.swing.JTextField();
        IDLibro3 = new javax.swing.JTextField();
        IDLibro4 = new javax.swing.JTextField();
        jB_AgregarLibro1 = new javax.swing.JButton();
        jB_AgregarLibro2 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 610));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/LOGO UAEMEX.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/facultad.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a Usuarios de la bibloteca");

        IdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdUsuarioActionPerformed(evt);
            }
        });

        IDLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel2.setText("Nombres:");

        jLabel3.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel3.setText("Apellidos Paterno:");

        jLabel6.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel6.setText("Apellido Marterno.");

        IDLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel7.setText("Edad:");

        jLabel8.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel8.setText("Ocupacion:");

        jLabel9.setFont(new java.awt.Font("SimSun", 2, 14)); // NOI18N
        jLabel9.setText("ID del Usuario:");

        IDLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro2ActionPerformed(evt);
            }
        });

        IDLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro3ActionPerformed(evt);
            }
        });

        IDLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro4ActionPerformed(evt);
            }
        });

        jB_AgregarLibro1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_AgregarLibro1.setText("Eliminar Usuario");
        jB_AgregarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarLibro1ActionPerformed(evt);
            }
        });

        jB_AgregarLibro2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_AgregarLibro2.setText("Agregar Usuario");
        jB_AgregarLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarLibro2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel3))
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(IDLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jB_AgregarLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel5)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jB_AgregarLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(IDLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLibro3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDLibro4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(IDLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_AgregarLibro2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jB_AgregarLibro1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 991, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro2ActionPerformed
        // TODO add your handling code here:
        //espacio para agregar apellido materno 
    }//GEN-LAST:event_IDLibro2ActionPerformed

    private void jB_AgregarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarLibro1ActionPerformed
        // TODO add your handling code here:
        //boton para eliminar usuario 
        String idUsuario = IDLibro.getText();
        if (idUsuario.isEmpty()) {
            //panel o ventana que nme 
            JOptionPane.showMessageDialog(this, "Por favor ingrese el ID del usuario a eliminar", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        } // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Está seguro que desea eliminar al usuario con ID: " + idUsuario + "?",
                "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            // Consulta SQL para eliminar el usuario
            String sql = "DELETE FROM Usuario WHERE id_usuario = ?";

            try (PreparedStatement ps = conexion.getConnection().prepareStatement(sql)) {
                ps.setInt(1, Integer.parseInt(idUsuario));  // Convertir el ID a número

                int filasAfectadas = ps.executeUpdate();

                if (filasAfectadas > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario eliminado correctamente",
                            "Éxito", JOptionPane.INFORMATION_MESSAGE);
                    limpiarCampos();  // Método para limpiar los campos del formulario
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontró el usuario con ID: " + idUsuario,
                            "Advertencia", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar usuario: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jB_AgregarLibro1ActionPerformed

    //boton para agregar usuario 
    private void jB_AgregarLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarLibro2ActionPerformed

        String nombre = IdUsuario.getText();
        String apellidoPaterno = IDLibro1.getText();
        String apellidoMaterno = IDLibro2.getText();
        String edad = IDLibro3.getText();
        String ocupacion = IDLibro4.getText();
        String idUsuario = IDLibro.getText();

        if (nombre.isEmpty() || apellidoPaterno.isEmpty() || idUsuario.isEmpty()
                || !idUsuario.matches("\\d+")) { // Validar que id.usuario sea numérico
            JOptionPane.showMessageDialog(this, "Por favor complete los campos obligatorios con datos válidos",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sql = "INSERT INTO Usuario (id_usuario, nombre, apellido_paterno, apellido_materno, edad, ocupacion) "
                    + "VALUES (?, ?, ?, ?, ?, ?)";// 6 parámetros para 6 campos

            try (PreparedStatement ps = conexion.getConnection().prepareStatement(sql)) {
                ps.setInt(1, Integer.parseInt(idUsuario));  // Convertir a número
                ps.setString(2, nombre);
                ps.setString(3, apellidoPaterno);
                ps.setString(4, apellidoMaterno);
                ps.setObject(5, edad.isEmpty() ? null : Integer.valueOf(edad), Types.INTEGER);
                ps.setString(6, ocupacion.isEmpty() ? null : ocupacion);

                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Usuario agregado correctamente");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar usuario: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID y edad deben ser números válidos");
        }
    }//GEN-LAST:event_jB_AgregarLibro2ActionPerformed

    private void IDLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro1ActionPerformed
        // TODO add your handling code here:
        //espacio para pone apellido paterno 
    }//GEN-LAST:event_IDLibro1ActionPerformed

    private void IDLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro3ActionPerformed
        // TODO add your handling code here:
        //espacio para poner edad

    }//GEN-LAST:event_IDLibro3ActionPerformed

    private void IDLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro4ActionPerformed
        // TODO add your handling code here:
        //espacio para poner la ocupacion de lusuario 
    }//GEN-LAST:event_IDLibro4ActionPerformed

    private void IDLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibroActionPerformed
        // TODO add your handling code here:
        //espacio para poner el id del usuario 
    }//GEN-LAST:event_IDLibroActionPerformed

    private void IdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdUsuarioActionPerformed
        // TODO add your handling code here:
        //espacio para que pongan nombre del usuario 
    }//GEN-LAST:event_IdUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLibro;
    private javax.swing.JTextField IDLibro1;
    private javax.swing.JTextField IDLibro2;
    private javax.swing.JTextField IDLibro3;
    private javax.swing.JTextField IDLibro4;
    private javax.swing.JTextField IdUsuario;
    private javax.swing.JButton jB_AgregarLibro1;
    private javax.swing.JButton jB_AgregarLibro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
