/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author angel
 */
import Conexiones.Conexion;
import Programa.Usuario;

public class VentanaUsuarios extends javax.swing.JPanel {

    private Conexion conexion;

    /**
     * Creates new form Principal1
     */
    public VentanaUsuarios() {

        initComponents();
        conexion = new Conexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        IDLibro1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDLibro2 = new javax.swing.JTextField();
        IDLibro3 = new javax.swing.JTextField();
        IDLibro4 = new javax.swing.JTextField();
        jB_AgregarLibro1 = new javax.swing.JButton();
        jB_AgregarLibro2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(990, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/LOGO UAEMEX.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/facultad.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, 169));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a Usuarios de la bibloteca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 24, -1, -1));

        IdUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        IdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 260, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombres:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 90, 33));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Apellido Paterno:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Apellido Marterno:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, 20));

        IDLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro1ActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 260, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ocupacion:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        IDLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro2ActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 260, 40));

        IDLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro3ActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 260, 40));

        IDLibro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro4ActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 260, 40));

        jB_AgregarLibro1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_AgregarLibro1.setText("Eliminar Usuario");
        jB_AgregarLibro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarLibro1ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_AgregarLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 216, 67));

        jB_AgregarLibro2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_AgregarLibro2.setText("Agregar Usuario");
        jB_AgregarLibro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarLibro2ActionPerformed(evt);
            }
        });
        jPanel1.add(jB_AgregarLibro2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 216, 67));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void IDLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro2ActionPerformed
        // TODO add your handling code here:
        //espacio para agregar apellido materno 
    }//GEN-LAST:event_IDLibro2ActionPerformed

    private void jB_AgregarLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarLibro1ActionPerformed
        // TODO add your handling code here:
        Usuario.eliminarUsuarioPorId();

    }//GEN-LAST:event_jB_AgregarLibro1ActionPerformed

    //boton para agregar usuario 
    private void jB_AgregarLibro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarLibro2ActionPerformed

        String nombre = IdUsuario.getText();
        String apellidoPaterno = IDLibro1.getText();
        String apellidoMaterno = IDLibro2.getText();
        String edad = IDLibro3.getText();
        String ocupacion = IDLibro4.getText();
        Usuario usuarioAgregado = Usuario.agregarUsuario(nombre, apellidoPaterno, apellidoMaterno, edad, ocupacion);

        if (usuarioAgregado != null) {
        }

    }//GEN-LAST:event_jB_AgregarLibro2ActionPerformed

    private void IDLibro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro1ActionPerformed
        // TODO add your handling code here:
        //espacio para pone apellido paterno 
    }//GEN-LAST:event_IDLibro1ActionPerformed

    private void IDLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro3ActionPerformed
        // TODO add your handling code here:
        //espacio para poner edad

    }//GEN-LAST:event_IDLibro3ActionPerformed

    private void IDLibro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro4ActionPerformed
        // TODO add your handling code here:
        //espacio para poner la ocupacion de lusuario 
    }//GEN-LAST:event_IDLibro4ActionPerformed

    private void IdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdUsuarioActionPerformed
        // TODO add your handling code here:
        //espacio para que pongan nombre del usuario 
    }//GEN-LAST:event_IdUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLibro1;
    private javax.swing.JTextField IDLibro2;
    private javax.swing.JTextField IDLibro3;
    private javax.swing.JTextField IDLibro4;
    private javax.swing.JTextField IdUsuario;
    private javax.swing.JButton jB_AgregarLibro1;
    private javax.swing.JButton jB_AgregarLibro2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
