/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Conexiones.Conexion;
import java.awt.Color;
import Conexiones.Conexion;
import Programa.Material;
import Programa.RegistrosImpl;
import Programa.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
//import com.healthmarketscience.jackcess.crypt.CryptCodecProvider;

import java.awt.Font;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Programa.EnlistarRegistrosUsuarios;
import Programa.MetodosEnlistarRegistrosLibros;

/**
 *
 * @author angel
 */
public class VentanaRegistros extends javax.swing.JPanel {

    /**
     * Creates new form Principal1
     */
    private javax.swing.JTextArea TTA_Libros;

    public VentanaRegistros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BotonParaEnlistarLibros = new javax.swing.JButton();
        BotonParaEnlistarUsuarios = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido al gestionador de la bibloteca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 27, 433, 24));

        BotonParaEnlistarLibros.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BotonParaEnlistarLibros.setText("Gestionar Libros");
        BotonParaEnlistarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaEnlistarLibrosActionPerformed(evt);
            }
        });
        jPanel1.add(BotonParaEnlistarLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 254, 67));

        BotonParaEnlistarUsuarios.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        BotonParaEnlistarUsuarios.setText("Gestionar Usuarios");
        BotonParaEnlistarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonParaEnlistarUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(BotonParaEnlistarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 254, 67));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 620, 180));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 620, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //boton para enlistar libros1 oficial 
    private void BotonParaEnlistarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaEnlistarLibrosActionPerformed
        // TODO add your handling code here
        try {
            // Llamamos al método llenarTablaLibros de la clase RegistrosImpl
            RegistrosImpl regImpl = new RegistrosImpl();
            DefaultTableModel modelo = regImpl.llenarTablaLibros();

            if (modelo != null) {
                // Asignamos el modelo al JTable
                jTable2.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudieron cargar los libros.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BotonParaEnlistarLibrosActionPerformed

    //boton para enlistar usuarios 
    private void BotonParaEnlistarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonParaEnlistarUsuariosActionPerformed
        // TODO add your handling code here:
        try {
            EnlistarRegistrosUsuarios regImpl = new EnlistarRegistrosUsuarios();
            DefaultTableModel modelo = regImpl.llenarTablaUsuarios();

            if (modelo != null) {
                jTable4.setModel(modelo);  // Asegúrate de que jTable4 es el nombre correcto
            } else {
                JOptionPane.showMessageDialog(this, "No se pudieron cargar los usuarios.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_BotonParaEnlistarUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonParaEnlistarLibros;
    private javax.swing.JButton BotonParaEnlistarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
