/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Programa.OperacionesLibros; // Aquí está la lógica para agregar y eliminar libros
import javax.swing.JOptionPane;
import java.sql.Date;

/**
 *
 * @author angel
 */
public class VentanaLibros extends javax.swing.JPanel {

    /**
     * Creates new form Principal1
     */
    public VentanaLibros() {
        initComponents(); // Método que construye toda la interfaz gráfica
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        IdUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jB_AgregarLibro = new javax.swing.JButton();
        IDLibro1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        IDLibro3 = new javax.swing.JTextField();
        IDLibro4 = new javax.swing.JTextField();
        jB_EliminarLibro = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/facultad.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/LOGO UAEMEX.jpg"))); // NOI18N

        setPreferredSize(new java.awt.Dimension(990, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 610));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Bienvenido a libros de la bibloteca ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 24, -1, -1));
        jPanel1.add(IdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 260, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nombre del Libro:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 133, 33));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Id Autor:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jB_AgregarLibro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_AgregarLibro.setText("Agregar Libro");
        jB_AgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_AgregarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(jB_AgregarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 216, 67));
        jPanel1.add(IDLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 260, 40));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Fecha de Lanzamiento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Id de Editorial:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        IDLibro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDLibro3ActionPerformed(evt);
            }
        });
        jPanel1.add(IDLibro3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 260, 40));
        jPanel1.add(IDLibro4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 260, 40));

        jB_EliminarLibro.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jB_EliminarLibro.setText("Eliminar Libro");
        jB_EliminarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EliminarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(jB_EliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 216, 67));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/facultad.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, -1, 169));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/LOGO UAEMEX.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //boton para agregar libro
    //el metodo que se ejecuta cuando el usuario hace clic en el botón 
    private void jB_AgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_AgregarLibroActionPerformed

        // Usamos try-catch para manejar errores si el usuario mete datos inválidos
        try {
            // Obtenemos el texto del campo donde se escribe el nombre del libro
            String nombre = IdUsuario.getText();
            // Obtenemos y convertimos el ID del autor a entero (porque viene como texto)
            int idAutor = Integer.parseInt(IDLibro1.getText());
            // Obtenemos y convertimos el ID de la editorial a entero
            int idEditorial = Integer.parseInt(IDLibro4.getText());

            // Obtenemos la fecha como texto, y reemplazamos "/" o "." por guiones
            // para que quede en formato yyyy-MM-dd (lo que necesita SQL)
            String fechaTexto = IDLibro3.getText().replace("/", "-").replace(".", "-");
            // Convertimos el texto ya corregido a un objeto de tipo Date (java.sql.Date)
            Date fechaSQL = Date.valueOf(fechaTexto);

            // Creamos una instancia de la clase que tiene la lógica para guardar libros
            OperacionesLibros op = new OperacionesLibros();
            // Llamamos al método que guarda el libro en la base de datos, pasándole los datos
            op.agregarLibro(nombre, idAutor, idEditorial, fechaSQL);

        } catch (IllegalArgumentException ex) {
            // Si ocurre un error (por ejemplo, fecha mal escrita), mostramos un mensaje
            JOptionPane.showMessageDialog(null, "Fecha inválida. Usa el formato yyyy-MM-dd (por ejemplo, 2001-03-15)");
        }
    }//GEN-LAST:event_jB_AgregarLibroActionPerformed

    //boton para eliminar libro  
    // Método que se ejecuta cuando se hace clic en el botón "Eliminar Libro"
    private void jB_EliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EliminarLibroActionPerformed
        
    // Creamos una nueva instancia de la clase que contiene la lógica para manejar los libros
        OperacionesLibros op = new OperacionesLibros(); 
         // Llamamos al método que se encarga de eliminar un libro de la base de datos
        op.eliminarLibro();
    }//GEN-LAST:event_jB_EliminarLibroActionPerformed

    private void IDLibro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDLibro3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDLibro3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDLibro1;
    private javax.swing.JTextField IDLibro3;
    private javax.swing.JTextField IDLibro4;
    private javax.swing.JTextField IdUsuario;
    private javax.swing.JButton jB_AgregarLibro;
    private javax.swing.JButton jB_EliminarLibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
